apiVersion: v1
kind: Namespace
metadata:
  name: klare-methode-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: klare-app-promo-site
  namespace: klare-methode-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klare-app-promo-site
  template:
    metadata:
      labels:
        app: klare-app-promo-site
    spec:
      containers:
        - name: website
          image: blisha234/klare-app-promo-site:latest
          imagePullPolicy: Always  # Zurück zu Always, um neues Image zu erzwingen
          startupProbe:            # Neue Startup-Sonde für langsame Starts
            httpGet:
              path: /
              port: http
            failureThreshold: 30   # Erlaubt bis zu 30 Fehler (300 Sekunden bei 10s Periode)
            periodSeconds: 10
          ports:
            - containerPort: 3000
              name: http
          # Environment variables
          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXT_PUBLIC_MAKE_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: klare-app-secrets
                  key: NEXT_PUBLIC_MAKE_WEBHOOK_URL
            - name: NEXT_PUBLIC_ADMIN_MODE
              value: "false"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1001  # Explizite numerische ID anstatt Name
            runAsGroup: 1001
            # Wir entfernen readOnlyRootFilesystem, da es Probleme mit dem Cache verursacht
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp  # Benötigt für temporäre Dateien
            - name: cache-volume
              mountPath: /app/.next/cache
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60  # Längere Verzögerung, um sicherzustellen, dass die App vollständig gestartet ist
            periodSeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 120  # Noch längere Verzögerung für Liveness
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 6  # Mehr Fehlversuche erlauben
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: cache-volume
          emptyDir: 
            medium: Memory  # Speichere den Cache im RAM für bessere Performance
            sizeLimit: 500Mi  # Begrenze die Größe des Caches
---
apiVersion: v1
kind: Secret
metadata:
  name: klare-app-secrets
  namespace: klare-methode-app
type: Opaque
data:
  # Base64 encoded value of the webhook URL from .env.local
  NEXT_PUBLIC_MAKE_WEBHOOK_URL: aHR0cHM6Ly9ob29rLmV1Mi5tYWtlLmNvbS9jcGNmZTg4bTFjNjU3cjdxczNvc2pkZmtwOTduZm5ubw==
---
apiVersion: v1
kind: Service
metadata:
  name: klare-app-promo-site
  namespace: klare-methode-app
  annotations:
    prometheus.io/scrape: "true"  # Zusätzliche Metriken
    prometheus.io/port: "3000"
spec:
  selector:
    app: klare-app-promo-site
  ports:
    - port: 80
      name: http
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
  publishNotReadyAddresses: false  # Stellen Sie sicher, dass nur bereite Pods Traffic erhalten
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: klare-app-promo-site
  namespace: klare-methode-app
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    # Erhöhte Timeouts für bessere Stabilität
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    # Verbesserte Upstream-Fehlerbehandlung
    nginx.ingress.kubernetes.io/proxy-next-upstream: "error timeout http_502 http_503 http_504"
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "3"
    # Standard Header zur Verbesserung der Sicherheit
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Content-Type-Options "nosniff" always;
      add_header X-Frame-Options "SAMEORIGIN" always;
      add_header X-XSS-Protection "1; mode=block" always;
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - klare-methode.app
        - www.klare-methode.app
      secretName: klare-methode-app-tls
  rules:
    - host: klare-methode.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: klare-app-promo-site
                port:
                  number: 80
    - host: www.klare-methode.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: klare-app-promo-site
                port:
                  number: 80
