apiVersion: v1
kind: Namespace
metadata:
  name: klare-methode-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: klare-app-promo-site
  namespace: klare-methode-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: klare-app-promo-site
  template:
    metadata:
      labels:
        app: klare-app-promo-site
    spec:
      containers:
        - name: website
          image: blisha234/klare-app-promo-site:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          # Environment variables
          env:
            - name: NEXT_PUBLIC_MAKE_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: klare-app-secrets
                  key: NEXT_PUBLIC_MAKE_WEBHOOK_URL
            - name: NEXT_PUBLIC_ADMIN_MODE
              value: "false"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "384Mi"
              cpu: "300m"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Secret
metadata:
  name: klare-app-secrets
  namespace: klare-methode-app
type: Opaque
data:
  # Base64 encoded value of the webhook URL from .env.local
  NEXT_PUBLIC_MAKE_WEBHOOK_URL: aHR0cHM6Ly9ob29rLmV1Mi5tYWtlLmNvbS9jcGNmZTg4bTFjNjU3cjdxczNvc2pkZmtwOTduZm5ubw==
---
apiVersion: v1
kind: Service
metadata:
  name: klare-app-promo-site
  namespace: klare-methode-app
spec:
  selector:
    app: klare-app-promo-site
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: klare-app-promo-site
  namespace: klare-methode-app
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    # Vereinfachte Cache-Konfiguration für K3s-Kompatibilität
    # Cache-Control Header mit kürzerer Caching-Zeit für JS-Dateien (1 Tag)
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header Cache-Control "public, max-age=86400";
    # Minimale Location-Direktiven für K3s mit verbesserten Cache-Einstellungen
    nginx.ingress.kubernetes.io/server-snippet: |
      # Bilder und statische Assets langfristig cachen
      location ~* \.(jpg|jpeg|png|gif|ico|css|svg)$ {
        add_header Cache-Control "public, max-age=604800, immutable";
      }
      # JS-Dateien mit kurzer Caching-Zeit und No-Cache für Chunks
      location ~* \.js$ {
        add_header Cache-Control "public, max-age=86400";
      }
      # Keine Caching für kritische Next.js-Chunk-Dateien
      location ~* /next/static/chunks/ {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires "0";
      }
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - klare-methode.app
        - www.klare-methode.app
      secretName: klare-methode-app-tls
  rules:
    - host: klare-methode.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: klare-app-promo-site
                port:
                  number: 80
    - host: www.klare-methode.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: klare-app-promo-site
                port:
                  number: 80

