apiVersion: v1
kind: Namespace
metadata:
  name: klare-methode-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: klare-app-promo-site
  namespace: klare-methode-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klare-app-promo-site
  template:
    metadata:
      labels:
        app: klare-app-promo-site
    spec:
      containers:
        - name: website
          image: blisha234/klare-app-promo-site:latest
          imagePullPolicy: IfNotPresent  # Reduziert unnötige Image-Pulls
          ports:
            - containerPort: 3000
              name: http
          # Environment variables
          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXT_PUBLIC_MAKE_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: klare-app-secrets
                  key: NEXT_PUBLIC_MAKE_WEBHOOK_URL
            - name: NEXT_PUBLIC_ADMIN_MODE
              value: "false"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "384Mi"
              cpu: "300m"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true  # Erhöht die Sicherheit
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp  # Benötigt für temporäre Dateien
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15  # Reduziert auf 15s für schnelleres Start-Feedback
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30  # Reduziert auf 30s für schnelleres Recovery
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: tmp-volume
          emptyDir: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: klare-app-secrets
  namespace: klare-methode-app
type: Opaque
data:
  # Base64 encoded value of the webhook URL from .env.local
  NEXT_PUBLIC_MAKE_WEBHOOK_URL: aHR0cHM6Ly9ob29rLmV1Mi5tYWtlLmNvbS9jcGNmZTg4bTFjNjU3cjdxczNvc2pkZmtwOTduZm5ubw==
---
apiVersion: v1
kind: Service
metadata:
  name: klare-app-promo-site
  namespace: klare-methode-app
spec:
  selector:
    app: klare-app-promo-site
  ports:
    - port: 80
      name: http
      targetPort: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: klare-app-promo-site
  namespace: klare-methode-app
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    # Nur grundlegende Sicherheits-Header, keine Cache-Anweisungen
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Content-Type-Options "nosniff" always;
      add_header X-Frame-Options "SAMEORIGIN" always;
      add_header X-XSS-Protection "1; mode=block" always;
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - klare-methode.app
        - www.klare-methode.app
      secretName: klare-methode-app-tls
  rules:
    - host: klare-methode.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: klare-app-promo-site
                port:
                  number: 80
    - host: www.klare-methode.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: klare-app-promo-site
                port:
                  number: 80
