apiVersion: v1
kind: Namespace
metadata:
  name: klare-methode-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: klare-app-promo-site
  namespace: klare-methode-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klare-app-promo-site
  template:
    metadata:
      labels:
        app: klare-app-promo-site
    spec:
      containers:
        - name: website
          image: blisha234/klare-app-promo-site:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          # Wenn es Umgebungsvariablen gibt, können diese hier hinzugefügt werden
          # env:
          # - name: NEXT_PUBLIC_MAKE_WEBHOOK_URL
          #   valueFrom:
          #     secretKeyRef:
          #       name: klare-app-secrets
          #       key: NEXT_PUBLIC_MAKE_WEBHOOK_URL
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
---
# Falls Secrets benötigt werden, würde man sie hier definieren
# apiVersion: v1
# kind: Secret
# metadata:
#   name: klare-app-secrets
#   namespace: klare-methode-app
# type: Opaque
# data:
#   # echo -n "https://api.example.com" | base64
#   NEXT_PUBLIC_MAKE_WEBHOOK_URL: aHR0cHM6Ly9hcGkuZXhhbXBsZS5jb20=
---
apiVersion: v1
kind: Service
metadata:
  name: klare-app-promo-site
  namespace: klare-methode-app
spec:
  selector:
    app: klare-app-promo-site
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: klare-app-promo-site
  namespace: klare-methode-app
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - klare-methode.app
        - www.klare-methode.app
      secretName: klare-methode-app-tls
  rules:
    - host: klare-methode.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: klare-app-promo-site
                port:
                  number: 80
    - host: www.klare-methode.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: klare-app-promo-site
                port:
                  number: 80

